### ISSUE TITLE
Problem with jsx bundle

### ISSUE THREAD

**Issue by fusionstrings** [tachun/diagramio#1]
I think this doesn't work.
https://github.com/tachun/diagramio/blob/7de11f724aeac907f19ab121550dec7b0c499c41/gulpfile.js#L161

**Comment by tachun** [comment]
Thanks, you are right it isn't a jsx file, I fixed it here:
https://github.com/tachun/diagramio/commit/c67a1e23e1d8aec6dc6957935aa907e753734758
